# Site settings
title: Julia Torrejon
description: A portfolio about my projects
baseurl: "/juliatorrejon.github.io" # the subpath of your site, e.g. /blog
url: "https://juliatorrejon.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Julia Torrejon
user_description: Think outside the box
user_title: Think outside the box
email: juliatorrejon0atgmail.com
twitter_username: JuliaTorrejon
github_username:  JuliaTorrejon

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
